### ISSUE TITLE
Is it possible to use this exporter to monitor PEM files within each pod?

### ISSUE THREAD

**Issue by Reyzorcat** [ribbybibby/ssl_exporter#146]
Is it possible to use this exporter to monitor PEM files within each pod?
As far as I understand from the documentation, PEM files can only be monitored locally from the exporter pod itself or from the host using a daemonset. I would like to be able to monitor files within each cluster pod

**Comment by ribbybibby** [comment]
I guess you might be able to run the exporter as a sidecar container in the pod and use a shared volume to share the certificates with the exporter: https://kubernetes.io/docs/tasks/access-application-cluster/communicate-containers-same-pod-shared-volume/. 

If your certificates are being mounted  from secrets in the cluster, you could use the [secret prober](https://github.com/ribbybibby/ssl_exporter?tab=readme-ov-file#kubernetes). In general it's probably better to mount certificates into pods like this anyway, rather than relying on them being in the container filesystem in the pod already.

Another option might be to look for files recursively on the node in [the 'merged' directory](https://blog.px.dev/container-filesystems/#method-4:-finding-the-filesystem-on-the-host):
```
curl "localhost:9219/probe?module=file&target=/var/lib/docker/overlay2/*/merged/**/*.pem"
```

This might be quite slow and you'd probably need pretty beefy permissions. I suppose you might also struggle to associate the path on disk back to the running pod. You might need to do some fancy label_replace stuff to associate the container id in the path back to a container in a pod.
