### ISSUE TITLE
insecure_skip_verify: true - does't work

### ISSUE THREAD

**Issue by kimabd** [ribbybibby/ssl_exporter#62]
Hello, I have set up `insecure_skip_verify: true`, but anyway I don't see all metrics and in log I get error below

`ERRO[0002] error=Get "https://<IP_ADDRESS>:443": x509: cannot validate certificate for <IP_ADDRESS> because it doesn't contain any IP SANs target=<IP_ADDRESS>:443 prober=https timeout=10s  source="ssl_exporter.go:93"
`

**Comment by kimabd** [comment]
sorry, have found same issue - https://github.com/ribbybibby/ssl_exporter/issues/60

**Comment by perlun** [comment]
@ribbybibby Since this issue seems to pop up from time to time (and I found it myself today since we are attempting to monitor two host with expired certificates :grin:), would it be worth making this the default? It seems like a quite legit use case for the exporter to want to do a "best effort" to ignore broken certificates etc., and instead log this brokenness as part of the exported metrics instead of failing the probe. :thinking:
